### ISSUE TITLE
AutoComplete dropdown is not scrollable

### ISSUE THREAD

**Issue by inceptivetech** [mrlaessig/react-native-autocomplete-input#64]
<TouchableOpacity onPress={() => { this.setState({ query: common_name }), this.onSelect(common_name)}}>
                <Text style={styles.itemText}>
                           {common_name}
                 </Text>
</TouchableOpacity>

This is me renderItem Code. Please help.

**Comment by whyxn** [comment]
Also having the same issue. My AutoComplete is inside a ScrollView and the suggestion list is not scrolling if I fix the height.

**Comment by emaLorenzo** [comment]
Could someone accomplish this?

**Comment by markmssd** [comment]
This solution worked for me #57

**Comment by SnaiNeR** [comment]
If your screen already have another wrap of scrollview, autocomplete's scrollview wouldn't work.
Change all ScrollViews in your screen to View beside Autocomplete's ScrollView and test again. If it work, just use [#57](https://github.com/l-urence/react-native-autocomplete-input/issues/57)

**Comment by nawif** [comment]
I really didn't like the way #57 fixed many because it made the code much more complex,
I fixed firstly by giving the 'renderItem' row a fixed height, mine was 70, after than in the listContainerStyle prop I gave it a height of  70 (single row height) multiplied by the length of the array, so in the end I ended up with this
' listContainerStyle={{height:filteredMembers.length * 70}} '
where filteredMembers is the data passed the the 'data' prop.
